package com.osiris.desku;

import com.osiris.desku.swing.events.LoadStateChange;
import com.osiris.desku.ui.Component;
import com.osiris.events.Event;
import com.osiris.jlib.logger.AL;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.locks.ReentrantLock;
import java.util.function.Consumer;

/**
 * Native window with HTML content that is generated by provided {@link Route}.
 */
public abstract class UI {
    private static final ReentrantLock access = new ReentrantLock();
    private static volatile UI current = null;
    public final AtomicBoolean isLoading = new AtomicBoolean(true);
    /**
     * Relevant when wanting HTML load state of {@link #browser}.
     */
    public final Event<LoadStateChange> onLoadStateChanged = new Event<>();
    /**
     * Last loaded html.
     */
    public final Route route;
    public final Component<?> content;
    /**
     * Not thread safe, access inside synchronized block.
     */
    public final HashMap<String, List<Component<?>>> listenersAndComps = new HashMap<>();

    public UI(Route route) throws IOException {
        this(route, false, 70, 60);
    }

    public UI(Route route, boolean isTransparent, int widthPercent, int heightPercent) throws IOException {
        access.lock();
        current = this;

        this.route = route;
        this.content = route.loadContent();
        onLoadStateChanged.addAction((e) -> {
            if (e.isLoading) return;
            isLoading.set(false);
        });

        current = null;
        access.unlock();

        priv_init("file:///" + snapshotToTempFile().getAbsolutePath(), isTransparent, widthPercent, heightPercent);
    }

    /**
     * Always null, except when code is running inside... <br>
     * - {@link #access(Runnable)} <br>
     * - constructor {@link #UI(Route, boolean, int, int)} when generating this UIs' HTML  for the first time. <br>
     * - any triggered JavaScript event that was registered via {@link #registerJSListener(String, Component, Consumer)}. <br>
     * or {@link #set(UI, Thread...)} was called before.
     */
    public static UI get() {
        if (current != null)
            return current;
        else {
            // Current code is not inside access(), thus we check the thread
            synchronized (threadsAndUIs) {
                return threadsAndUIs.get(Thread.currentThread());
            }
        }
    }

    private static final Map<Thread, UI> threadsAndUIs = new HashMap<>();

    /**
     * Maps the provided threads to the provided UI, so that when calling
     * {@link UI#get()} inside those threads it returns the provided UI.
     */
    public static void set(UI ui, Thread... threads) {
        synchronized (threadsAndUIs) {
            for (Thread t : threads) {
                threadsAndUIs.put(t, ui);
            }
        }
    }

    public static void remove(Thread... threads) {
        synchronized (threadsAndUIs) {
            for (Thread t : threads) {
                threadsAndUIs.remove(t);
            }
        }
    }

    /**
     * Access this window synchronously now.
     * Also sets {@link #current} to this window.
     */
    public UI access(Runnable code) {
        access.lock();
        current = this;
        code.run();
        current = null;
        access.unlock();
        return this;
    }

    /**
     * Initialises/Displays the window and loads the HTML from the provided startURL.
     *
     * @param startURL      URL of the HTML content. Example: http://localhost or https://google.com or file:///ABSOLUTE_PATH_TO_HTML_FILE
     * @param isTransparent
     * @param widthPercent
     * @param heightPercent
     */
    public abstract void init(String startURL, boolean isTransparent, int widthPercent, int heightPercent) throws Exception;

    private void priv_init(String startURL, boolean isTransparent, int widthPercent, int heightPercent) {
        try {
            AL.info("Starting new window with url: " + startURL + " transparent: " + isTransparent + " width: " + widthPercent + "% height: " + heightPercent + "%");
            AL.info("Please stand by...");
            UIManager.uis.add(this);
            long ms = System.currentTimeMillis();
            init(startURL, isTransparent, widthPercent, heightPercent);
            AL.info("Init took " + (System.currentTimeMillis() - ms) + "ms for " + this);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public void close() {
        UIManager.uis.remove(this);
    }

    /**
     * Creates a snapshot of the current UI (the full HTML page) <br>
     * and returns it as {@link Document} for further processing. <br>
     * Note that changes to it won't be reflected in the actual UI.
     */
    public Document getSnapshot() {
        Document html = route.getDocument();
        Element outlet = html.getElementById("outlet");
        content.updateAll();
        outlet.appendChild(content.element);
        return html;
    }

    public File getDir() {
        // TODO in testing this resolves to the same directory after restarting even though it should be a new one
        // this results in cached files in that directory like images not getting updated, if changed.
        File dir = new File(App.tempDir + "/" + Integer.toHexString(hashCode()));
        dir.mkdirs();
        return dir;
    }

    /**
     * @see #snapshotToTempFile(Document)
     */
    public File snapshotToTempFile() throws IOException {
        return snapshotToTempFile(null);
    }

    /**
     * Creates a snapshot and writes the HTML to a file in the temp folder of the current user. <br>
     * If the path for this route is "/persons/john" for example then the html file will be created at: <br>
     * {@link App#tempDir}/{@link #hashCode()}/persons/john.html <br>
     * Note that the hash code is in hex format.
     *
     * @return the generated html file.
     */
    public File snapshotToTempFile(Document snapshot) throws IOException {
        File file = new File(getDir()
                + (route.path.equals("/") ? "/root.html" : (route.path + ".html")));
        if (snapshot == null) snapshot = getSnapshot();

        // Create symbolic link in current folder to global-styles.css
        // Symbolic links can't be created in temp folder?
        File link = new File(file.getParentFile() + "/" + App.styles.getName());
        AL.info("Copy of global styles: " + link);
        synchronized (App.styles) {
            if (!link.exists()) {
                link.getParentFile().mkdirs();
                link.createNewFile();
            }
            Files.copy(App.styles.toPath(), link.toPath(), StandardCopyOption.REPLACE_EXISTING);
        }
        Element elLink = new Element("link");
        elLink.attr("rel", "stylesheet");
        elLink.attr("href", App.styles.getName());
        snapshot.getElementsByTag("head").get(0).appendChild(elLink);

        // Write html to temp file
        AL.info("Generate: " + file);
        file.getParentFile().mkdirs();
        if (!file.exists()) file.createNewFile();
        Files.write(file.toPath(), snapshot.outerHtml().getBytes(StandardCharsets.UTF_8));
        return file;
    }

    /**
     * @see #width(int)
     */
    public void widthFull() {
        width(100);
    }

    /**
     * This invalidates the container and thus to see changes in the UI
     * make sure execute {@link java.awt.Component#revalidate()} manually.
     *
     * @param widthPercent 0 to 100% of the parent size (screen if null).
     */
    public abstract void width(int widthPercent);

    /**
     * @see #height(int)
     */
    public void heightFull() {
        height(100);
    }

    /**
     * This invalidates the container and thus to see changes in the UI
     * make sure execute {@link java.awt.Component#revalidate()} manually.
     *
     * @param heightPercent 0 to 100% of the parent size (screen if null).
     */
    public abstract void height(int heightPercent);

    /**
     * Moves the window on the X axis.
     *
     * @param x amount to add to current x value.
     */
    public abstract void plusX(int x);

    /**
     * Moves the window on the Y axis.
     *
     * @param y amount to add to current y value.
     */
    public abstract void plusY(int y);

    public abstract void executeJavaScript(String jsCode, String jsCodeSourceName, int jsCodeStartingLineNumber);

    /**
     * Returns new JS (JavaScript) code, that when executed in client browser
     * results in onJSFunctionExecuted being executed. <br>
     * It wraps around your jsCode and adds callback related stuff, as well as error handling.
     *
     * @param jsCode               modify the message variable in the provided JS (JavaScript) code to send information from JS to Java.
     *                             Your JS code could look like this: <br>
     *                             message = 'first second third etc...';
     * @param onJSFunctionExecuted executed when the provided jsCode executes successfully. String contains the message variable that can be set in your jsCode.
     * @param onJsFunctionFailed   executed when the provided jsCode threw an exception. String contains details about the exception/error.
     */
    public abstract String addCallback(String jsCode, Consumer<String> onJSFunctionExecuted, Consumer<String> onJsFunctionFailed);

    public String jsGetComp(String varName, int id) {
        return "var " + varName + " = document.querySelectorAll('[java-id=\"" + id + "\"]')[0];\n";
    }

    /**
     * Registers this listener directly only if the page was loaded,
     * otherwise adds an action to {@link #onLoadStateChanged} to register the listener later.
     *
     * @param eventName name of the JavaScript event to listen for.
     * @param comp      component to register the listener on.
     * @param onEvent   executed when event happened. Has {@link #access(Runnable)}.
     */
    public <T> UI registerJSListener(String eventName, Component<T> comp, Consumer<String> onEvent) {
        synchronized (listenersAndComps) {
            List<Component<?>> alreadyRegisteredComps = listenersAndComps.get(eventName);
            if (alreadyRegisteredComps == null) {
                alreadyRegisteredComps = new ArrayList<>();
                listenersAndComps.put(eventName, alreadyRegisteredComps);
            }
            if (alreadyRegisteredComps.contains(comp))
                return this; // Already registered
            alreadyRegisteredComps.add(comp);
        }
        String jsNow = jsGetComp("comp", comp.id) +
                "comp.addEventListener(\"" + eventName + "\", (event) => {\n" +
                addCallback("function getObjProps(obj) {\n" +
                                "  var s = '{';\n" +
                                "  for (const key in obj) {\n" +
                                "    if (obj[key] !== obj && obj[key] !== null && obj[key] !== undefined) {\n" +
                                "      s += (`\"${key}\": \"${obj[key]}\",`);\n" +
                                "    }\n" +
                                "  }\n" +
                                "  if(s[s.length-1] == ',') s = s.slice(0, s.length-1);" + // Remove last ,
                                "  s += '}';\n" +
                                "  return s;\n" +
                                "}" +
                                "message = getObjProps(event)\n",
                        (message) -> {
                            access(() -> {
                                onEvent.accept(message); // Should execute all listeners
                            });
                        },
                        (error) -> {
                            throw new RuntimeException(error);
                        }) + // JS code that triggers Java function gets executed on a click event for this component
                "});\n";

        if (!isLoading.get()) executeJavaScript(jsNow, "internal", 0);
        else onLoadStateChanged.addAction((action, event) -> {
            if (event.isLoading) return;
            action.remove();
            executeJavaScript(jsNow, "internal", 0);
        }, AL::warn);
        return this;
    }
}
