package com.osiris.desku.ui;

import com.osiris.desku.App;
import com.osiris.desku.Route;
import com.osiris.desku.swing.Swing;
import com.osiris.desku.ui.utils.Rectangle;
import com.osiris.jlib.logger.AL;
import dev.webview.Webview;
import dev.webview.platform.OperatingSystem;
import dev.webview.platform.Platform;

import javax.swing.*;
import java.awt.Component;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Consumer;

/**
 * Native window with HTML content that is generated by provided {@link Route}.
 */
public class DesktopUI extends UI {
    public JFrame frame;
    public Webview browser;
    public java.awt.Canvas browserContainer;

    public DesktopUI(Route route) throws Exception {
        this(route, false, 70, 60);
    }

    public DesktopUI(Route route, boolean isTransparent, int widthPercent, int heightPercent) throws Exception {
        super(route, isTransparent, widthPercent, heightPercent);
    }

    /**
     * Initialises/Displays the window and loads the HTML from the provided startURL.
     * To display a simple browser window, it suffices completely to create an
     * instance of the class CefBrowser and to assign its DesktopUI component to your
     * application (e.g. to your content pane).
     * But to be more verbose, this CTOR keeps an instance of each object on the
     * way to the browser DesktopUI.
     *
     * @param startURL      URL of the HTML content. Example: http://localhost or https://google.com or file:///ABSOLUTE_PATH_TO_HTML_FILE
     * @param isTransparent
     * @param widthPercent
     * @param heightPercent
     */
    public void init(String startURL, boolean isTransparent, int widthPercent, int heightPercent) throws Exception {
        AtomicBoolean isLoaded = new AtomicBoolean(false);
        onLoadStateChanged.addAction((action, isLoading) -> {
            if (!isLoading) {
                action.remove();
                isLoaded.set(true);
            }
        }, Exception::printStackTrace);

        frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        frame.setLayout(new BorderLayout());

        // Using createAWT allows you to defer the creation of the webview until the
        // canvas is fully renderable.
        browserContainer = (Canvas) Webview.createAWT(true, (wv) -> {
            browser = wv;

            wv.bind("tellJavaThatIsLoaded", e -> {
                onLoadStateChanged.execute(false); // stopped loading
                return null;
            });
            wv.loadURL(startURL);
            wv.eval("const event = new Event(\"pageloaded\");\n" +
                    "async function notifyOnPageLoad() {\n" +
                    "  setTimeout(function() {  \n" +
                    "    if (document.readyState === 'complete') {\n" +
                    "        console.log('Page finished loading.');\n" +
                    "        window.tellJavaThatIsLoaded().then(result => {});\n" +
                    "        document.dispatchEvent(event);\n" +
                    "    } else {\n" +
                    "      notifyOnPageLoad();\n" +
                    "    }\n" +
                    "  }, 100) // 100ms\n" +
                    "}\n" +
                    "console.log('Waiting for page to finish loading...')\n" +
                    "notifyOnPageLoad()\n");

            // Resize browser window too
            frame.addComponentListener(new ComponentAdapter() {
                @Override
                public void componentResized(ComponentEvent e) {
                    Dimension contentSize = e.getComponent().getSize();
                    // Exclude decoration/top-bar from width/height
                    Insets insets = frame.getInsets();
                    int contentWidth = contentSize.width - insets.left - insets.right;
                    int contentHeight = contentSize.height - insets.top - insets.bottom;
                    // There is a random margin on Windows that isn't visible, so we must
                    // compensate. // TODO figure out why this is caused.
                    if (Platform.os == OperatingSystem.WINDOWS) {
                        contentWidth -= 16;
                        contentHeight -= 39;
                    }
                    int finalContentWidth = contentWidth;
                    int finalContentHeight = contentHeight;
                    wv.dispatch(() -> {
                        wv.setFixedSize(finalContentWidth, finalContentHeight);
                        //browserContainer.setSize(finalContentWidth, finalContentHeight); // This somehow breaks stuff
                    });
                }
            });

            frame.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    close();
                }
            });

            // Run the webview event loop, the webview is fully disposed when this returns.
            wv.run();
        });

        frame.getContentPane().add(browserContainer, BorderLayout.CENTER);
        if (widthPercent <= 0 || heightPercent <= 0) {
            widthPercent = 100;
            heightPercent = 100;
        }
        width(widthPercent);
        height(heightPercent);
        frame.setIconImage(App.getIcon());
        frame.setTitle(App.name);
        Swing.center(frame);
        frame.revalidate();
        frame.setFocusable(true);
        frame.setVisible(true);
        frame.requestFocus();

        // JavaScript cannot be executed before the page is loaded
        while (!isLoaded.get()) Thread.yield();
    }

    @Override
    public void close() {
        browser.close();
        frame.dispose();
        super.close();
        if (com.osiris.desku.ui.UIManager.all.isEmpty()) System.exit(0);
    }

    /**
     * This invalidates the container and thus to see changes in the DesktopUI
     * make sure execute {@link java.awt.Component#revalidate()} manually.
     *
     * @param widthPercent 0 to 100% of the parent size (screen if null).
     */
    public void width(int widthPercent) {
        if (frame == null) onLoadStateChanged.addAction((action, isLoading) -> {
            if (!isLoading) {
                action.remove();
                updateWidth(frame.getParent(), frame, widthPercent);
            }
        }, AL::warn);
        else
            updateWidth(frame.getParent(), frame, widthPercent);
    }

    /**
     * This invalidates the container and thus to see changes in the DesktopUI
     * make sure execute {@link java.awt.Component#revalidate()} manually.
     *
     * @param heightPercent 0 to 100% of the parent size (screen if null).
     */
    public void height(int heightPercent) {
        if (frame == null) onLoadStateChanged.addAction((action, isLoading) -> {
            if (!isLoading) {
                action.remove();
                updateHeight(frame.getParent(), frame, heightPercent);
            }
        }, AL::warn);
        else
            updateHeight(frame.getParent(), frame, heightPercent);
    }

    private void updateWidth(java.awt.Component parent, java.awt.Component target, int widthPercent) {
        int parentWidth; // If no parent provided use the screen dimensions
        if (parent != null) parentWidth = parent.getWidth();
        else parentWidth =
                GraphicsEnvironment.isHeadless() ? 1920 // FHD
                        : Toolkit.getDefaultToolkit().getScreenSize().width;
        Dimension size = new Dimension(parentWidth / 100 * widthPercent, target.getHeight());
        target.setSize(size);
        target.setPreferredSize(size);
        target.setMaximumSize(size);
    }

    private void updateHeight(java.awt.Component parent, Component target, int heightPercent) {
        int parentHeight; // If no parent provided use the screen dimensions
        if (parent != null) parentHeight = parent.getHeight();
        else parentHeight =
                GraphicsEnvironment.isHeadless() ? 1080 // FHD
                        : Toolkit.getDefaultToolkit().getScreenSize().height;
        Dimension size = new Dimension(target.getWidth(), parentHeight / 100 * heightPercent);
        target.setSize(size);
        target.setPreferredSize(size);
        target.setMaximumSize(size);
    }

    public void plusX(int x) {
        frame.setLocation(frame.getX() + x, frame.getY());
    }

    public void plusY(int y) {
        frame.setLocation(frame.getX(), frame.getY() + y);
    }

    @Override
    public void executeJavaScript(String jsCode, String jsCodeSourceName, int jsCodeStartingLineNumber) {
        browser.dispatch(() -> {
            browser.eval(jsCode);
        });
    }

    @Override
    public void maximize(boolean b) {
        frame.setExtendedState(b ? JFrame.MAXIMIZED_BOTH : JFrame.NORMAL);
    }

    @Override
    public void minimize(boolean b) {
        frame.setExtendedState(b ? JFrame.ICONIFIED : JFrame.NORMAL);
    }

    @Override
    public void fullscreen(boolean b) {
        GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices()[0];
        device.setFullScreenWindow(b ? frame : null);
    }

    @Override
    public void onSizeChange(Consumer<com.osiris.desku.ui.utils.Rectangle> code) {
        frame.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                code.accept(new com.osiris.desku.ui.utils.Rectangle(
                        e.getComponent().getWidth(), e.getComponent().getHeight()));
                frame.revalidate();
            }
        });
    }

    @Override
    public Rectangle getScreenSize() {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        GraphicsConfiguration gc = gd.getDefaultConfiguration();
        java.awt.Rectangle screenSize = gc.getBounds();
        Insets screenInsets = Toolkit.getDefaultToolkit().getScreenInsets(gc);

        int width = screenSize.width - screenInsets.left - screenInsets.right;
        int height = screenSize.height - screenInsets.top - screenInsets.bottom;
        return new Rectangle(width, height);
    }

    @Override
    public Rectangle getScreenSizeWithoutTaskBar() {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        GraphicsConfiguration gc = gd.getDefaultConfiguration();
        java.awt.Rectangle screenSize = gc.getBounds();
        Insets screenInsets = Toolkit.getDefaultToolkit().getScreenInsets(gc);
        // TODO if window has decoration, add it to this calculation

        int width = screenSize.width - screenInsets.left - screenInsets.right;
        int height = screenSize.height - screenInsets.top - screenInsets.bottom;
        return new Rectangle(screenSize.width - width, screenSize.height - height);
    }

    @Override
    public void decorate(boolean b) {
        if(frame.isDisplayable()){
            boolean wasVisible = frame.isVisible(); // Check if the frame was visible
            frame.setVisible(false); // Hide the frame
            frame.dispose(); // Dispose of the frame
            frame.setUndecorated(!b); // Set the decoration flag
            frame.pack(); // Pack the frame
            frame.setVisible(wasVisible);
        } else{
            frame.setUndecorated(!b);
        }
    }

    @Override
    public void allwaysOnTop(boolean b) {
        frame.setAlwaysOnTop(b);
    }

    @Override
    public void focus(boolean b) {
        if(b) frame.requestFocus();
        else frame.transferFocusBackward();
    }

    public Color convertCSSColor(String cssHexColor) {
        if (cssHexColor.startsWith("#")) {
            // Remove the # symbol from the beginning
            cssHexColor = cssHexColor.substring(1);
        }

        int alpha = 255; // Default alpha value (fully opaque)
        if (cssHexColor.length() == 8) {
            // Extract the alpha value from the last two characters
            String alphaHex = cssHexColor.substring(6);
            alpha = Integer.parseInt(alphaHex, 16);
        }

        int red = Integer.parseInt(cssHexColor.substring(0, 2), 16);
        int green = Integer.parseInt(cssHexColor.substring(2, 4), 16);
        int blue = Integer.parseInt(cssHexColor.substring(4, 6), 16);

        return new Color(red, green, blue, alpha);
    }

    @Override
    public void background(String hexColor) {
        Color color = convertCSSColor(hexColor);
        frame.setBackground(color);
        frame.getContentPane().setBackground(color);
        if(content != null) content.putStyle("background-color", hexColor);
    }
}
